# Practical_6: Numpy

In [2]:
import numpy as np

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [5]:
# Exercise 1
w=np.arange(1,11)
print(w)

[ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [6]:
# Exercise 2
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [8]:
# Exercise 3
m=10
n=5
array_num=np.linspace(0,n,m)
array_num = np.interp(
    np.linspace(0, m- 1, m),
    np.arange(len(array_num)),
    array_num
).astype(int)
print(array_num)

[0 0 1 1 2 2 3 3 4 5]



---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [9]:
# Exercise 4
matrix_5=np.eye(5)
print(matrix_5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [11]:
# Exercise 5
matrix_4 = np.random.rand(4, 4)
print(matrix_4)

[[0.29450918 0.73156666 0.85731256 0.05455441]
 [0.37096317 0.74235553 0.30868668 0.96447119]
 [0.68099493 0.98562642 0.35705746 0.93204975]
 [0.26172458 0.97988585 0.13586397 0.28941587]]



---

### Exercise 6:
Find the shape of a NumPy array.


In [12]:
# Exercise 6
a=np.array([[9,6,3,4],[4,5,7,6]])
print(a.shape)


(2, 4)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [14]:
# Exercise 7
k=np.arange(16)
matrix=k.reshape(4,4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [16]:
# Exercise 8
m=np.array([1,2,4,5,6,7])
print(type(m))

<class 'numpy.ndarray'>



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [17]:
# Exercise 9
x=np.arange(1,101)
even_numbers=x[x %2==0]
print(even_numbers)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [18]:
# Exercise 10
matrix_6x6 = np.random.randint(10, 51, size=(6, 6))
print(matrix_6x6)

[[21 28 43 19 13 37]
 [37 16 50 35 38 26]
 [22 29 19 25 34 21]
 [34 23 21 42 16 20]
 [49 41 15 24 13 17]
 [40 16 10 27 35 22]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [19]:
# Exercise 11
matrix = np.arange(25).reshape(5, 5)
print("Original matrix:")
print(matrix)

submatrix = matrix[1:4, 1:4]
print("\nSubmatrix (3x3 from center):")
print(submatrix)

Original matrix:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Submatrix (3x3 from center):
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]



---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [21]:
# Exercise 12
x = np.array([[4, 6], [8, 9]])
y = np.array([[2, 31], [4, 5]])

print(np.add(x, y))

[[ 6 37]
 [12 14]]



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [24]:
# Exercise 13
x=np.array([1,3,6,8,8,7,8,25])
x_mean=np.mean(x)
print('mean_is=',x_mean)

x_median=np.median(x)
print('median_is=',x_median)

x_standard=np.std(x)
print('standard deviation_is=',x_standard)


mean_is= 8.25
median_is= 7.5
standard deviation_is= 6.777720855862979



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [25]:
# Exercise 14
x=np.array([1,3,6,8,8,7,8,25])
x_max=np.max(x)
x_min=np.min(x)
print(x_max)
print(x_min)

25
1



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [28]:
# Exercise 15
x=np.random.randint(1,50,size=20)
max_x=np.argmax(x)
print(x)
print('=============')

print(len(x))
print('=============')
print(x[max_x])
print('=============')
print(max_x)

[18 26 16 17  2 32  1 26 11 15 25 31  1  5 45 47 37 42 26 39]
20
47
15



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [29]:
# Exercise 16
x=np.array([1,3,6,8,8,7,8,25])
x_reverse=x[::-1]
print(x_reverse)

[25  8  7  8  8  6  3  1]



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [32]:
# Exercise 17
x=np.array([[1,2,3],[2,8,9],[2,3,4]])
y=np.array([[2,4,5],[2,4,5],[3,2,1]])
print(x)
print('==========')
print(y)
print('==========')
print(np.dot(x,y))

[[1 2 3]
 [2 8 9]
 [2 3 4]]
[[2 4 5]
 [2 4 5]
 [3 2 1]]
[[15 18 18]
 [47 58 59]
 [22 28 29]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [33]:
# Exercise 18


arr = np.array([1, 2, 3, 4])
diag_matrix = np.diag(arr)
print(diag_matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [35]:
# Exercise 19
x=np.array([[1,2],[3,4]])
y=np.array([[3,5],[6,7]])
solution=np.dot(x,y)
print('x matrix:\n',x)
print('==========')
print('y matrix:\n',y)
print('==========')
print('solution matrix:\n',solution)

x matrix:
 [[1 2]
 [3 4]]
y matrix:
 [[3 5]
 [6 7]]
solution matrix:
 [[15 19]
 [33 43]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [38]:
# Exercise 20
m=np.array([[5,6,7],[8,9,10]])
n=m.flatten()
print('2D IS:\n',m)
print('1D IS:\n',n)

2D IS:
 [[ 5  6  7]
 [ 8  9 10]]
1D IS:
 [ 5  6  7  8  9 10]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [40]:
# Exercise 21
a=np.array([[10,5],[11,7]])
b=np.array([[5,6],[7,8]])

stack_vertical=np.vstack((a,b))
print('x :\n',a)
print('========')
print('y :\n',b)
print('========')
print('Vertical stack:\n',stack_vertical)

x :
 [[10  5]
 [11  7]]
y :
 [[5 6]
 [7 8]]
Vertical stack:
 [[10  5]
 [11  7]
 [ 5  6]
 [ 7  8]]



---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [41]:
# Exercise 22
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

stack_horzontal=np.hstack((x,y))
print('x :\n',x)
print('y :\n',y)
print('Horzontal stack:\n',stack_horzontal)

x :
 [[1 2]
 [3 4]]
y :
 [[5 6]
 [7 8]]
Horzontal stack:
 [[1 2 5 6]
 [3 4 7 8]]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [45]:
# Exercise 23
x=np.array([4,6,7,8,11,12])
x_split=np.split(x,3)
print(x_split)

[array([4, 6]), array([7, 8]), array([11, 12])]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [48]:
# Exercise 24
a=np.random.rand(3,3)
a_round=np.round(a,2)
print(a)
print("======================\n")
print(x_round)

[[0.32433204 0.16418949 0.84597639]
 [0.90120819 0.0408225  0.37835828]
 [0.24943555 0.59590575 0.66970527]]

[[0.74 0.11 0.39]
 [0.04 0.64 0.55]
 [0.83 0.22 0.6 ]]



---

### Exercise 25:
Find the unique elements of a NumPy array.


In [49]:
# Exercise 25
x=np.array([2,2,3,4,5,6,7,8,3,4])
x_unique=np.unique(x)
print(x_unique)

[2 3 4 5 6 7 8]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [50]:
# Exercise 26
x=np.array([1,2,3,4,5,6,7,8])
x[x <4]=4
print(x)

[4 4 4 4 5 6 7 8]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [52]:
# Exercise 27
y=np.array([1,2,3,4,5])
cumulative_sum_y=np.cumsum(y)
print('Y is:\n',y)
print('Cumulative sum:\n',cumulative_sum_y)

Y is:
 [1 2 3 4 5]
Cumulative sum:
 [ 1  3  6 10 15]



---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [53]:
# Exercise 28
x=np.array([1,10,2,0,7,0,9])
non_xero_x=np.count_nonzero(x)
print(x)
print(non_xero_x)

[ 1 10  2  0  7  0  9]
5



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [55]:
# Exercise 29
x=np.random.randint(1,19,size=20)
Ascending_x=np.sort(x)
print(x)
print(Ascending_x)

[ 7 17  9  7  8 11  6  7 10  5 17 17  5 18  4  2  6 14 12  6]
[ 2  4  5  5  6  6  6  7  7  7  8  9 10 11 12 14 17 17 17 18]



---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [57]:
# Exercise 30
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
row_wise=np.sum(x,axis=1)
column_wise=np.sum(x,axis=0)
print('X is:\n',x)
print('========')
print('Row wise:\n',row_wise)
print('========')
print('Column wise:\n',column_wise)

X is:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Row wise:
 [ 6 15 24]
Column wise:
 [12 15 18]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [58]:
# Exercise 31
x=np.random.randint(10,100,size=(3,4))
x_min=x.min()
x_max=x.max()
normalize_x=(x - x_min)/(x_max - x_min)
print("x is:\n",x)
print("=================================")
print("normarlize for x is:\n",normalize_x)

x is:
 [[46 45 97 44]
 [64 31 30 17]
 [86 13 99 15]]
normarlize for x is:
 [[0.38372093 0.37209302 0.97674419 0.36046512]
 [0.59302326 0.20930233 0.19767442 0.04651163]
 [0.84883721 0.         1.         0.02325581]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [60]:
# Exercise 32
# Exercise 33
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Compute dot product
dot_product = np.dot(a, b)

print("Array a:", a)
print('=========')
print("Array b:", b)
print('=========')
print("Dot product:", dot_product)

Array a: [1 2 3]
Array b: [4 5 6]
Dot product: 32



---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [62]:
# Exercise 33
matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

# Calculate the trace
trace_value = np.trace(matrix)

print("Matrix:\n", matrix)
print("Trace of the matrix:", trace_value)

Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace of the matrix: 15



---

### Exercise 34:
Create a 2D array and swap two rows.


In [64]:
# Exercise 34
matrix = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])

print("Original matrix:")
print(matrix)

# Swap row 0 and row 2
matrix[[0, 2]] = matrix[[2, 0]]

print("Matrix after swapping row 0 and row 2:")
print(matrix)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix after swapping row 0 and row 2:
[[7 8 9]
 [4 5 6]
 [1 2 3]]



---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [65]:
# Exercise 35
array_1d = np.array([3, 4, 5, 6, 7])

column_vector = array_1d.reshape(-1, 1)

print("Column vector:")
print(column_vector)

Column vector:
[[3]
 [4]
 [5]
 [6]
 [7]]



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [68]:
# Exercise 36
matrix = np.array([
    [4, 3, 2],
    [3, 1, 5],
    [1, 0, 6]
])

determinant = np.linalg.det(matrix)

print("Matrix:\n", matrix)
print('=========================')
print("Determinant of the matrix:", determinant)

Matrix:
 [[4 3 2]
 [3 1 5]
 [1 0 6]]
Determinant of the matrix: -17.0



---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [69]:
# Exercise 37
matrix = np.array([[1, 2],
                   [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Eigenvalues:
[-0.37228132  5.37228132]

Eigenvectors:
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [70]:
# Exercise 38
A = np.array([[10, 13],
              [3, 4]])

B = np.array([8, 11])

solution = np.linalg.solve(A, B)

print("Solution [x, y]:", solution)

Solution [x, y]: [-111.   86.]



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [73]:
# Exercise 39
# Create an original array
original_array = np.array([[10, 20, 30],[40, 50, 60], [70, 80, 90]])

noise = np.random.normal(loc=0, scale=5, size=original_array.shape)


noisy_array = original_array + noise

print("Original array:\n", original_array)
print("\nGaussian noise:\n", noise)
print("\nNoisy array:\n", noisy_array)

Original array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Gaussian noise:
 [[ 6.11257678 -9.20387498 -2.39445078]
 [-4.14813854 11.12840641  1.35867431]
 [-2.91581286 -0.01630821 -0.17017665]]

Noisy array:
 [[16.11257678 10.79612502 27.60554922]
 [35.85186146 61.12840641 61.35867431]
 [67.08418714 79.98369179 89.82982335]]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [74]:
# Exercise 40
matrix = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120],
    [130, 140, 150, 160]
])


diagonal_elements = np.diag(matrix)

print("Matrix:\n", matrix)
print("\nDiagonal elements:", diagonal_elements)

Matrix:
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]

Diagonal elements: [ 10  60 110 160]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [75]:
# Exercise 41
start=10
stop=50
size=100
a=np.random.randint(start,stop,size)
print(a)
print(len(a))

[33 13 36 12 14 22 21 46 18 22 14 46 15 14 47 32 26 29 26 14 25 40 34 12
 31 33 45 41 22 29 33 11 22 16 23 17 20 31 47 21 28 28 32 39 30 49 40 35
 48 20 46 28 15 27 30 27 14 25 44 49 46 23 27 14 21 12 17 41 42 23 46 11
 47 38 18 16 43 31 26 18 19 44 24 28 41 34 39 34 46 34 21 14 32 41 27 38
 43 49 28 23]
100



---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [76]:
# Exercise 42
x=np.array([[3,-10,2],[-9,7,-2]])
x[x <0]= 0
print(x)

[[3 0 2]
 [0 7 0]]



---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [80]:
# Exercise 43

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

inner_product = np.inner(a, b)

outer_product = np.outer(a, b)

print("Array a:", a)
print("Array b:", b)
print("Inner product:", inner_product)
print('==============================')
print("nOuter product:\n", outer_product)

Array a: [1 2 3]
Array b: [4 5 6]
Inner product: 32
nOuter product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [84]:
# Exercise 44
from scipy.spatial import distance_matrix
points = np.array([[0, 0],
                   [3, 3],
                   [2, 0]])
dist_matrix = distance_matrix(points, points)

print("Pairwise distance matrix:")
print(dist_matrix)

Pairwise distance matrix:
[[0.         4.24264069 2.        ]
 [4.24264069 0.         3.16227766]
 [2.         3.16227766 0.        ]]



---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [86]:
# Exercise 45
person_dtype = np.dtype([('name', 'U20'), 
                         ('age', 'i4'),    
                         ('height', 'f4')]) 

people = np.array([('Alice', 25, 5.5),
                   ('Bob', 30, 6.0),
                   ('Charlie', 22, 5.8)], dtype=person_dtype)

print(people)

[('Alice', 25, 5.5) ('Bob', 30, 6. ) ('Charlie', 22, 5.8)]



---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [88]:
# Exercise 46
matrix = np.random.randint(0, 10, size=(5, 5))

print("Matrix:")
print(matrix)
print('====================')

unique_values, counts = np.unique(matrix, return_counts=True)

for val, count in zip(unique_values, counts):
    print(f"Value {val} occurs {count} times")


Matrix:
[[8 3 7 1 2]
 [7 3 5 3 9]
 [2 5 7 1 5]
 [5 4 1 0 4]
 [9 3 2 8 2]]
Value 0 occurs 1 times
Value 1 occurs 3 times
Value 2 occurs 4 times
Value 3 occurs 4 times
Value 4 occurs 2 times
Value 5 occurs 4 times
Value 7 occurs 3 times
Value 8 occurs 2 times
Value 9 occurs 2 times



---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [89]:
# Exercise 47
arr = np.random.rand(3, 3)
row_means = arr.mean(axis=1, keepdims=True)
result = arr - row_means
print('Array is:\n',arr)
print("=================")
print("Mean is\n",row_means)
print("=================")
print("Result is:\n",result)

Array is:
 [[0.69265606 0.60152835 0.85904402]
 [0.30438084 0.10708141 0.80321603]
 [0.85021543 0.48851244 0.47887619]]
Mean is
 [[0.71774281]
 [0.40489276]
 [0.60586802]]
Result is:
 [[-0.02508675 -0.11621446  0.14130121]
 [-0.10051192 -0.29781135  0.39832327]
 [ 0.24434741 -0.11735558 -0.12699183]]



---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [91]:
# Exercise 48
arr= np.random.randint(0, 1000, size=10)
any_greater_than_50 = np.any(arr > 50)

print(arr)
print("Any values greater than 50:", any_greater_than_50)

[855 460 728 242 800 478 995 487 207 935]
Any values greater than 50: True



---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [92]:
# Exercise 49
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

window_size = 3

moving_avg = np.convolve(arr, np.ones(window_size) / window_size, mode='valid')

print("Original array:\n", arr)
print("\nMoving average (window size = 3):\n", moving_avg)

Original array:
 [1 2 3 4 5 6 7 8 9]

Moving average (window size = 3):
 [2. 3. 4. 5. 6. 7. 8.]



---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [94]:
# Exercise 50
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 11, 12, 13, 14])

correlation = np.corrcoef(a, b)[0, 1]


print("Pearson correlation coefficient:", correlation)

Pearson correlation coefficient: 0.9999999999999999



---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [97]:
# Exercise 51
radians = np.array([0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi])
degrees = np.degrees(radians)

print(degrees)



[  0.  90. 180. 270. 360.]



---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [99]:
# Exercise 52
arr = np.random.rand(30)
variance = np.var(arr)
std_dev = np.std(arr)

print("Array:", arr)
print("Variance:", variance)
print("Standard Deviation:", std_dev)

Array: [0.43217052 0.47446503 0.27569562 0.63488052 0.16073147 0.77789807
 0.76447848 0.10973576 0.1612009  0.56714789 0.88143653 0.45685008
 0.68374934 0.4604006  0.37257309 0.41445054 0.61855865 0.57435348
 0.22612367 0.35761508 0.34768634 0.39564995 0.19106846 0.01134228
 0.89232788 0.77698162 0.99464496 0.77400221 0.01361717 0.14780775]
Variance: 0.07237615208217806
Standard Deviation: 0.26902816224733433



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [101]:
# Exercise 53
arr = np.random.rand(1,2)
max_indices_axis0 = np.argmax(arr, axis=0)
max_indices_axis1 = np.argmax(arr, axis=1)

print("Array:\n", arr)
print("Indices of max values along axis 0:", max_indices_axis0)
print("Indices of max values along axis 1:", max_indices_axis1)

Array:
 [[0.78333742 0.06718989]]
Indices of max values along axis 0: [0 0]
Indices of max values along axis 1: [0]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [102]:
# Exercise 54
matrix = np.array([[1, 2],
                   [3, 4]])

inverse = np.linalg.inv(matrix)

print("Inverse matrix:")
print(inverse)

Inverse matrix:
[[-2.   1. ]
 [ 1.5 -0.5]]



---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [103]:
# Exercise 55
num_arr = np.random.rand(10)
standardized = (num_arr - np.mean(num_arr)) / np.std(num_arr)

print("Original array:", num_arr)
print("Standardized array:", standardized)

Original array: [0.82313271 0.27019091 0.92795813 0.98574809 0.7393909  0.59076458
 0.44317636 0.15221851 0.18698416 0.27303565]
Standardized array: [ 0.94617313 -0.89683135  1.29556565  1.48818476  0.66705421  0.17166938
 -0.32025538 -1.29004392 -1.1741669  -0.88734957]



---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [105]:
# Exercise 56
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

addition = a + b
subtraction = a - b

print("Addition:", addition)
print('========================')
print("Subtraction:", subtraction)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [111]:
# Exercise 57
arr = np.random.rand(5)
max_index = np.argmax(arr)

print("Array:", arr)
print('======================================')
print("Index of maximum element:", max_index)

Array: [0.16362681 0.29501618 0.8948069  0.68303874 0.6639162 ]
Index of maximum element: 2



---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [112]:
# Exercise 58

matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])


rotated_matrix = np.rot90(matrix)

print("Original matrix:\n", matrix)
print("\nRotated matrix (90 degrees counterclockwise):\n", rotated_matrix)


Original matrix:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Rotated matrix (90 degrees counterclockwise):
 [[30 60 90]
 [20 50 80]
 [10 40 70]]



---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [113]:
# Exercise 59
matrix = np.array([[10, 20],
                   [30, 40]])

frobenius_norm = np.linalg.norm(matrix, 'fro')

print("Frobenius norm:", frobenius_norm)

Frobenius norm: 54.772255750516614



---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [116]:
# Exercise 60
arr_num = np.arange(27).reshape((3, 3, 3))

subarray = arr_num[1:, :2, 1:]

print("Original array:\n", arr_num)
print('==============================')
print("\nSliced subarray:\n", subarray)

Original array:
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Sliced subarray:
 [[[10 11]
  [13 14]]

 [[19 20]
  [22 23]]]



---